services:
  web:
    build: .
    image: capcut-regaccc:latest
    container_name: capcut-regaccc
    command: xvfb-run -a /opt/venv/bin/python src/web/app.py
    ports:
      - "5050:5050"
    volumes:
      - ./data:/app/capcut-regaccc/data
    shm_size: "2gb"        # Firefox cần /dev/shm lớn, tránh crash
    mem_limit: "4g"
    restart: unless-stopped
